behaviors:
  MazeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size:              512
      buffer_size:             2048
      learning_rate:           1.0e-4
      beta:                    0.02
      epsilon:                 0.2
      lambd:                   0.95
      num_epoch:               3
      learning_rate_schedule:  constant
    network_settings:
      normalize:               true
      hidden_units:            128
      num_layers:              2
      memory:
        memory_size:           128
        sequence_length:       64
    reward_signals:
      extrinsic:
        strength:             1.0
        gamma:                0.99
      curiosity:              # Intrinsic Curiosity Module (ICM)
        strength:             0.02    # Poids de l’intrinsèque
        gamma:                0.99
        encoding_size:        256     # Taille de l’encodage pour l’ICM
    max_steps:                500000
    time_horizon:             1000
    summary_freq:             10000
